FROM mcr.microsoft.com/devcontainers/dotnet:1-10.0
RUN apt-get update && apt-get install -y --no-install-recommends python3 python3-pip libx11-6 libice6 libsm6 libfontconfig1 && rm -rf /var/lib/apt/lists/*
